import { IPO } from './types';

export const MOCK_IPOS: IPO[] = [
  {
    id: '1',
    name: 'TechNova Solutions Ltd',
    symbol: 'TECHNOVA',
    status: 'Active',
    openDate: '2023-10-25',
    closeDate: '2023-10-28',
    listingDate: '2023-11-04',
    priceBand: '₹450 - ₹480',
    lotSize: 30,
    issueSize: '850 Cr',
    gmp: 120,
    gmpUpdateDate: 'Today, 10:00 AM',
    subscription: {
      qib: 12.5,
      nii: 45.2,
      retail: 8.4,
      total: 18.2,
    },
    description: 'TechNova is a leading provider of AI-driven cloud infrastructure services, focusing on enterprise scalability and security solutions.',
    strengths: [
      'Strong revenue growth of 40% CAGR',
      'Debt-free company',
      'Marquee client base including Fortune 500 companies'
    ],
    risks: [
      'High client concentration',
      'Rapidly changing technology landscape'
    ],
    financials: {
      revenue: '₹1,200 Cr',
      profit: '₹180 Cr',
      margin: '15%',
    }
  },
  {
    id: '2',
    name: 'GreenEarth Energy',
    symbol: 'GREENERGY',
    status: 'Active',
    openDate: '2023-10-26',
    closeDate: '2023-10-29',
    listingDate: '2023-11-06',
    priceBand: '₹110 - ₹125',
    lotSize: 120,
    issueSize: '2,400 Cr',
    gmp: 15,
    gmpUpdateDate: 'Today, 09:30 AM',
    subscription: {
      qib: 2.1,
      nii: 1.5,
      retail: 3.2,
      total: 2.4,
    },
    description: 'GreenEarth Energy specializes in renewable solar and wind power generation assets across Western India.',
    strengths: [
      'Government backing and subsidies',
      'Long-term PPA agreements'
    ],
    risks: [
      'Capital intensive projects',
      'Regulatory hurdles in land acquisition'
    ],
    financials: {
      revenue: '₹3,500 Cr',
      profit: '₹220 Cr',
      margin: '6.2%',
    }
  },
  {
    id: '3',
    name: 'Urban Logistics',
    symbol: 'URBANLOG',
    status: 'Upcoming',
    openDate: '2023-11-01',
    closeDate: '2023-11-03',
    listingDate: '2023-11-10',
    priceBand: '₹200 - ₹215',
    lotSize: 65,
    issueSize: '600 Cr',
    gmp: 45,
    gmpUpdateDate: 'Yesterday',
    subscription: {
      qib: 0,
      nii: 0,
      retail: 0,
      total: 0,
    },
    description: 'Urban Logistics provides last-mile delivery solutions for e-commerce giants.',
    strengths: ['Asset-light model', 'Pan-India presence'],
    risks: ['Low entry barrier', 'Fuel price volatility'],
    financials: {
      revenue: '₹800 Cr',
      profit: '₹45 Cr',
      margin: '5.6%',
    }
  },
  {
    id: '4',
    name: 'BlueSky Finance',
    symbol: 'BLUESKY',
    status: 'Closed',
    openDate: '2023-10-15',
    closeDate: '2023-10-18',
    listingDate: '2023-10-24',
    priceBand: '₹800 - ₹850',
    lotSize: 15,
    issueSize: '1,500 Cr',
    gmp: 350,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 85.5,
      nii: 140.2,
      retail: 45.0,
      total: 95.4,
    },
    listingPrice: 1200,
    currentPrice: 1450,
    description: 'A non-banking financial company focused on housing finance in tier-2 cities.',
    strengths: ['High asset quality', 'Robust collection mechanism'],
    risks: ['Interest rate cycles', 'Credit defaults'],
    financials: {
      revenue: '₹4,200 Cr',
      profit: '₹650 Cr',
      margin: '15.5%',
    }
  },
  {
    id: '5',
    name: 'Quantum Biotech',
    symbol: 'QBIO',
    status: 'Upcoming',
    openDate: '2023-11-05',
    closeDate: '2023-11-08',
    listingDate: '2023-11-15',
    priceBand: '₹320 - ₹340',
    lotSize: 40,
    issueSize: '450 Cr',
    gmp: 0,
    gmpUpdateDate: 'Awaiting',
    subscription: {
      qib: 0,
      nii: 0,
      retail: 0,
      total: 0,
    },
    description: 'Research-led biotechnology firm developing specialized generic injectables.',
    strengths: ['Strong R&D capabilities', 'USFDA approved facilities'],
    risks: ['Regulatory audits', 'Pricing pressure in US market'],
    financials: {
      revenue: '₹300 Cr',
      profit: '₹80 Cr',
      margin: '26%',
    }
  },
  {
    id: '6',
    name: 'Apex Construction',
    symbol: 'APEXCON',
    status: 'Closed',
    openDate: '2023-09-10',
    closeDate: '2023-09-13',
    listingDate: '2023-09-21',
    priceBand: '₹200 - ₹210',
    lotSize: 70,
    issueSize: '500 Cr',
    gmp: 50,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 15.2,
      nii: 25.4,
      retail: 10.1,
      total: 18.5,
    },
    listingPrice: 260,
    currentPrice: 240,
    description: 'A leading construction firm specializing in highway and bridge infrastructure projects.',
    strengths: ['Strong order book', 'Experienced management'],
    risks: ['Raw material price volatility', 'Project delays'],
    financials: {
      revenue: '₹1,500 Cr',
      profit: '₹120 Cr',
      margin: '8.0%',
    }
  },
  {
    id: '7',
    name: 'Zenith Healthcare',
    symbol: 'ZENHEALTH',
    status: 'Closed',
    openDate: '2023-08-05',
    closeDate: '2023-08-08',
    listingDate: '2023-08-17',
    priceBand: '₹450 - ₹480',
    lotSize: 30,
    issueSize: '1,200 Cr',
    gmp: 10,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 2.5,
      nii: 1.8,
      retail: 0.9,
      total: 1.9,
    },
    listingPrice: 490,
    currentPrice: 520,
    description: 'Zenith Healthcare operates a chain of multi-specialty hospitals in North India.',
    strengths: ['High average revenue per bed', 'Expansion plans'],
    risks: ['High competition', 'Regulatory caps on pricing'],
    financials: {
      revenue: '₹950 Cr',
      profit: '₹85 Cr',
      margin: '9.0%',
    }
  },
  {
    id: '8',
    name: 'Rapid Delivery Systems',
    symbol: 'RAPIDDEL',
    status: 'Closed',
    openDate: '2023-07-20',
    closeDate: '2023-07-23',
    listingDate: '2023-07-31',
    priceBand: '₹80 - ₹85',
    lotSize: 175,
    issueSize: '300 Cr',
    gmp: 90,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 65.4,
      nii: 110.2,
      retail: 55.8,
      total: 82.5,
    },
    listingPrice: 175,
    currentPrice: 160,
    description: 'Tech-enabled logistics company focusing on hyperlocal delivery services.',
    strengths: ['High growth sector', 'Scalable technology platform'],
    risks: ['Cash burn', 'Intense competition'],
    financials: {
      revenue: '₹400 Cr',
      profit: '-₹25 Cr',
      margin: '-6.2%',
    }
  },
  {
    id: '9',
    name: 'SolarWinds Power',
    symbol: 'SOLWIN',
    status: 'Closed',
    openDate: '2023-06-15',
    closeDate: '2023-06-18',
    listingDate: '2023-06-26',
    priceBand: '₹120 - ₹130',
    lotSize: 115,
    issueSize: '800 Cr',
    gmp: 20,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 5.6,
      nii: 8.2,
      retail: 4.5,
      total: 6.1,
    },
    listingPrice: 150,
    currentPrice: 180,
    description: 'SolarWinds Power manufactures solar panels and related components.',
    strengths: ['Govt incentives for solar', 'Export potential'],
    risks: ['Dependency on imported raw materials', 'Policy changes'],
    financials: {
      revenue: '₹600 Cr',
      profit: '₹40 Cr',
      margin: '6.7%',
    }
  },
  {
    id: '10',
    name: 'FinTech Capital',
    symbol: 'FINCAP',
    status: 'Closed',
    openDate: '2023-05-25',
    closeDate: '2023-05-28',
    listingDate: '2023-06-05',
    priceBand: '₹500 - ₹520',
    lotSize: 28,
    issueSize: '2,000 Cr',
    gmp: 150,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 45.0,
      nii: 60.5,
      retail: 25.0,
      total: 48.2,
    },
    listingPrice: 670,
    currentPrice: 800,
    description: 'A digital lending platform connecting borrowers with institutional investors.',
    strengths: ['Proprietary credit scoring model', 'Low NPA levels'],
    risks: ['Regulatory tightening', 'Cybersecurity threats'],
    financials: {
      revenue: '₹2,500 Cr',
      profit: '₹450 Cr',
      margin: '18.0%',
    }
  },
  {
    id: '11',
    name: 'Ocean Blue Ports',
    symbol: 'OBPORTS',
    status: 'Closed',
    openDate: '2023-04-10',
    closeDate: '2023-04-13',
    listingDate: '2023-04-21',
    priceBand: '₹300 - ₹315',
    lotSize: 45,
    issueSize: '3,500 Cr',
    gmp: 5,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 1.5,
      nii: 1.1,
      retail: 0.8,
      total: 1.2,
    },
    listingPrice: 320,
    currentPrice: 310,
    description: 'Operator of private ports and terminals on the east coast.',
    strengths: ['Strategic location', 'Long-term cargo contracts'],
    risks: ['Dependency on global trade volume', 'Environmental regulations'],
    financials: {
      revenue: '₹5,000 Cr',
      profit: '₹600 Cr',
      margin: '12.0%',
    }
  },
  {
    id: '12',
    name: 'CyberSafe Security',
    symbol: 'CYBSAFE',
    status: 'Closed',
    openDate: '2023-03-05',
    closeDate: '2023-03-08',
    listingDate: '2023-03-16',
    priceBand: '₹600 - ₹650',
    lotSize: 20,
    issueSize: '600 Cr',
    gmp: 200,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 90.5,
      nii: 150.8,
      retail: 80.2,
      total: 110.5,
    },
    listingPrice: 850,
    currentPrice: 920,
    description: 'Provider of cybersecurity solutions for enterprises and government agencies.',
    strengths: ['High demand for security', 'Recurring revenue model'],
    risks: ['Talent shortage', 'Rapid technological obsolescence'],
    financials: {
      revenue: '₹450 Cr',
      profit: '₹90 Cr',
      margin: '20.0%',
    }
  },
  {
    id: '13',
    name: 'AgroTech Industries',
    symbol: 'AGROTECH',
    status: 'Closed',
    openDate: '2023-02-15',
    closeDate: '2023-02-18',
    listingDate: '2023-02-26',
    priceBand: '₹150 - ₹160',
    lotSize: 90,
    issueSize: '400 Cr',
    gmp: 30,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 8.5,
      nii: 12.4,
      retail: 6.8,
      total: 9.5,
    },
    listingPrice: 190,
    currentPrice: 210,
    description: 'Manufacturer of agricultural machinery and irrigation systems.',
    strengths: ['Rural economy focus', 'Wide distribution network'],
    risks: ['Monsoon dependency', 'Raw material costs'],
    financials: {
      revenue: '₹700 Cr',
      profit: '₹55 Cr',
      margin: '7.8%',
    }
  },
  {
    id: '14',
    name: 'Metro Retail Chains',
    symbol: 'METRORET',
    status: 'Closed',
    openDate: '2023-01-20',
    closeDate: '2023-01-23',
    listingDate: '2023-02-01',
    priceBand: '₹90 - ₹95',
    lotSize: 150,
    issueSize: '1,000 Cr',
    gmp: -5,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 0.9,
      nii: 0.5,
      retail: 0.6,
      total: 0.7,
    },
    listingPrice: 90,
    currentPrice: 85,
    description: 'Value retail chain operating in tier-2 and tier-3 cities.',
    strengths: ['Cost efficiency', 'Growing middle class'],
    risks: ['E-commerce competition', 'Inventory management'],
    financials: {
      revenue: '₹1,800 Cr',
      profit: '₹20 Cr',
      margin: '1.1%',
    }
  },
  {
    id: '15',
    name: 'Elite Hospitality',
    symbol: 'ELITEHOS',
    status: 'Closed',
    openDate: '2022-12-10',
    closeDate: '2022-12-13',
    listingDate: '2022-12-21',
    priceBand: '₹250 - ₹270',
    lotSize: 55,
    issueSize: '900 Cr',
    gmp: 40,
    gmpUpdateDate: 'Closed',
    subscription: {
      qib: 10.2,
      nii: 15.6,
      retail: 8.9,
      total: 11.5,
    },
    listingPrice: 310,
    currentPrice: 350,
    description: 'Luxury hotel chain with properties in major tourist destinations.',
    strengths: ['Post-pandemic travel boom', 'Premium brand value'],
    risks: ['Economic downturn', 'High maintenance costs'],
    financials: {
      revenue: '₹1,100 Cr',
      profit: '₹150 Cr',
      margin: '13.6%',
    }
  },
  // 10 NEW DUMMY CLOSED IPOS
  {
    id: '16',
    name: 'OmniComm Systems',
    symbol: 'OMNICOMM',
    status: 'Closed',
    openDate: '2022-11-05',
    closeDate: '2022-11-08',
    listingDate: '2022-11-16',
    priceBand: '₹180 - ₹200',
    lotSize: 75,
    issueSize: '550 Cr',
    gmp: 80,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 35.5, nii: 55.2, retail: 22.1, total: 38.4 },
    listingPrice: 285,
    currentPrice: 310,
    description: 'Unified communications platform provider for small businesses.',
    strengths: ['Scalable SaaS model', 'Global client base'],
    risks: ['Data privacy regulations', 'High churn rate'],
    financials: { revenue: '₹600 Cr', profit: '₹90 Cr', margin: '15.0%' }
  },
  {
    id: '17',
    name: 'BioLife Sciences',
    symbol: 'BIOLIFE',
    status: 'Closed',
    openDate: '2022-10-12',
    closeDate: '2022-10-15',
    listingDate: '2022-10-24',
    priceBand: '₹550 - ₹580',
    lotSize: 25,
    issueSize: '1,100 Cr',
    gmp: 120,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 62.1, nii: 88.5, retail: 34.2, total: 60.5 },
    listingPrice: 710,
    currentPrice: 650,
    description: 'Biotechnology firm focused on sustainable agricultural solutions.',
    strengths: ['Patented technology', 'Growing organic market'],
    risks: ['Regulatory hurdles', 'Seasonality'],
    financials: { revenue: '₹850 Cr', profit: '₹120 Cr', margin: '14.1%' }
  },
  {
    id: '18',
    name: 'AutoMotive Gears Ltd',
    symbol: 'AUTOGEAR',
    status: 'Closed',
    openDate: '2022-09-20',
    closeDate: '2022-09-23',
    listingDate: '2022-10-01',
    priceBand: '₹320 - ₹340',
    lotSize: 40,
    issueSize: '750 Cr',
    gmp: 25,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 5.5, nii: 7.2, retail: 3.1, total: 5.4 },
    listingPrice: 365,
    currentPrice: 420,
    description: 'Manufacturer of precision gears for the automotive industry.',
    strengths: ['Established OEM relationships', 'Capacity expansion'],
    risks: ['Cyclical auto industry', 'Raw material costs'],
    financials: { revenue: '₹1,200 Cr', profit: '₹150 Cr', margin: '12.5%' }
  },
  {
    id: '19',
    name: 'FreshFoods Retail',
    symbol: 'FRESHFOOD',
    status: 'Closed',
    openDate: '2022-08-15',
    closeDate: '2022-08-18',
    listingDate: '2022-08-27',
    priceBand: '₹120 - ₹130',
    lotSize: 110,
    issueSize: '400 Cr',
    gmp: 10,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 1.8, nii: 2.5, retail: 1.9, total: 2.1 },
    listingPrice: 135,
    currentPrice: 125,
    description: 'Chain of gourmet grocery stores in metropolitan areas.',
    strengths: ['Premium brand positioning', 'High margins'],
    risks: ['Supply chain disruptions', 'Perishable inventory'],
    financials: { revenue: '₹550 Cr', profit: '₹30 Cr', margin: '5.5%' }
  },
  {
    id: '20',
    name: 'BuildInfra Ltd',
    symbol: 'BUILDINF',
    status: 'Closed',
    openDate: '2022-07-05',
    closeDate: '2022-07-08',
    listingDate: '2022-07-16',
    priceBand: '₹240 - ₹250',
    lotSize: 60,
    issueSize: '950 Cr',
    gmp: 40,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 12.4, nii: 18.2, retail: 9.5, total: 13.8 },
    listingPrice: 295,
    currentPrice: 380,
    description: 'Construction and infrastructure development company.',
    strengths: ['Strong order book', 'Government contracts'],
    risks: ['Execution delays', 'Labor shortages'],
    financials: { revenue: '₹2,100 Cr', profit: '₹180 Cr', margin: '8.6%' }
  },
  {
    id: '21',
    name: 'DigitalPayments Corp',
    symbol: 'DIGIPAY',
    status: 'Closed',
    openDate: '2022-06-10',
    closeDate: '2022-06-13',
    listingDate: '2022-06-22',
    priceBand: '₹750 - ₹800',
    lotSize: 18,
    issueSize: '2,500 Cr',
    gmp: 180,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 42.5, nii: 58.2, retail: 25.4, total: 40.8 },
    listingPrice: 990,
    currentPrice: 1150,
    description: 'Leading digital payments gateway and fintech solutions.',
    strengths: ['Market leadership', 'Network effects'],
    risks: ['Regulatory changes', 'Competition'],
    financials: { revenue: '₹3,500 Cr', profit: '₹420 Cr', margin: '12.0%' }
  },
  {
    id: '22',
    name: 'GreenPower Gen',
    symbol: 'GREENPOW',
    status: 'Closed',
    openDate: '2022-05-20',
    closeDate: '2022-05-23',
    listingDate: '2022-06-01',
    priceBand: '₹90 - ₹100',
    lotSize: 150,
    issueSize: '1,800 Cr',
    gmp: 5,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 3.2, nii: 2.1, retail: 4.5, total: 3.5 },
    listingPrice: 102,
    currentPrice: 145,
    description: 'Renewable energy producer focusing on wind farms.',
    strengths: ['Green energy incentives', 'Long-term PPAs'],
    risks: ['Weather dependency', 'Grid connectivity issues'],
    financials: { revenue: '₹1,500 Cr', profit: '₹110 Cr', margin: '7.3%' }
  },
  {
    id: '23',
    name: 'HealthCare Plus',
    symbol: 'HEALTHPLS',
    status: 'Closed',
    openDate: '2022-04-15',
    closeDate: '2022-04-18',
    listingDate: '2022-04-27',
    priceBand: '₹400 - ₹420',
    lotSize: 35,
    issueSize: '800 Cr',
    gmp: 60,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 25.6, nii: 38.4, retail: 15.2, total: 26.5 },
    listingPrice: 485,
    currentPrice: 510,
    description: 'Diagnostic chain and pathology labs network.',
    strengths: ['Growing health awareness', 'Asset-light expansion'],
    risks: ['Pricing pressure', 'Quality control risks'],
    financials: { revenue: '₹900 Cr', profit: '₹160 Cr', margin: '17.8%' }
  },
  {
    id: '24',
    name: 'EduTech Learning',
    symbol: 'EDUTECH',
    status: 'Closed',
    openDate: '2022-03-10',
    closeDate: '2022-03-13',
    listingDate: '2022-03-22',
    priceBand: '₹150 - ₹160',
    lotSize: 90,
    issueSize: '300 Cr',
    gmp: -10,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 0.8, nii: 0.6, retail: 0.9, total: 0.85 },
    listingPrice: 145,
    currentPrice: 130,
    description: 'Online test preparation and skill development platform.',
    strengths: ['Scalable content', 'Large addressable market'],
    risks: ['Customer acquisition costs', 'Return to offline education'],
    financials: { revenue: '₹250 Cr', profit: '-₹40 Cr', margin: '-16.0%' }
  },
  {
    id: '25',
    name: 'ChemSynth Organics',
    symbol: 'CHEMSYN',
    status: 'Closed',
    openDate: '2022-02-05',
    closeDate: '2022-02-08',
    listingDate: '2022-02-17',
    priceBand: '₹600 - ₹630',
    lotSize: 22,
    issueSize: '650 Cr',
    gmp: 150,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 55.4, nii: 82.1, retail: 40.5, total: 58.6 },
    listingPrice: 790,
    currentPrice: 950,
    description: 'Specialty chemicals manufacturer for pharma and agro industries.',
    strengths: ['Niche product portfolio', 'Export driven'],
    risks: ['Environmental compliance', 'Raw material volatility'],
    financials: { revenue: '₹800 Cr', profit: '₹140 Cr', margin: '17.5%' }
  },
  {
    id: '26',
    name: 'Skyline Logistics',
    symbol: 'SKYLOG',
    status: 'Closed',
    openDate: '2022-01-05',
    closeDate: '2022-01-07',
    listingDate: '2022-01-17',
    priceBand: '₹180 - ₹190',
    lotSize: 80,
    issueSize: '420 Cr',
    gmp: 35,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 12.1, nii: 18.3, retail: 9.1, total: 13.5 },
    listingPrice: 215,
    currentPrice: 230,
    description: 'Pan-India logistics company focused on multimodal freight.',
    strengths: ['Nationwide network', 'Tech-enabled tracking'],
    risks: ['Fuel cost volatility', 'Working capital needs'],
    financials: { revenue: '₹1,050 Cr', profit: '₹95 Cr', margin: '9.0%' }
  },
  {
    id: '27',
    name: 'Polaris Renewables',
    symbol: 'POLREN',
    status: 'Closed',
    openDate: '2021-12-12',
    closeDate: '2021-12-15',
    listingDate: '2021-12-24',
    priceBand: '₹260 - ₹275',
    lotSize: 55,
    issueSize: '1,100 Cr',
    gmp: 65,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 28.6, nii: 34.2, retail: 14.5, total: 26.7 },
    listingPrice: 330,
    currentPrice: 360,
    description: 'Renewable energy platform with hybrid solar-wind parks.',
    strengths: ['Long-term PPAs', 'Diverse asset mix'],
    risks: ['Grid curtailment', 'Weather dependency'],
    financials: { revenue: '₹1,900 Cr', profit: '₹210 Cr', margin: '11.1%' }
  },
  {
    id: '28',
    name: 'Vertex Analytics',
    symbol: 'VERTEXA',
    status: 'Closed',
    openDate: '2021-11-20',
    closeDate: '2021-11-23',
    listingDate: '2021-12-02',
    priceBand: '₹540 - ₹560',
    lotSize: 24,
    issueSize: '850 Cr',
    gmp: 110,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 45.2, nii: 70.5, retail: 31.4, total: 48.3 },
    listingPrice: 720,
    currentPrice: 690,
    description: 'Advanced analytics SaaS for BFSI risk modeling.',
    strengths: ['Sticky enterprise clients', 'High gross margins'],
    risks: ['US dollar exposure', 'Talent retention'],
    financials: { revenue: '₹980 Cr', profit: '₹220 Cr', margin: '22.5%' }
  },
  {
    id: '29',
    name: 'Harbor Marine Services',
    symbol: 'HARBOR',
    status: 'Closed',
    openDate: '2021-10-10',
    closeDate: '2021-10-13',
    listingDate: '2021-10-21',
    priceBand: '₹310 - ₹325',
    lotSize: 60,
    issueSize: '600 Cr',
    gmp: 20,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 6.5, nii: 8.4, retail: 4.1, total: 6.9 },
    listingPrice: 345,
    currentPrice: 320,
    description: 'Port maintenance and marine engineering specialist.',
    strengths: ['Long-term contracts', 'Specialized crew'],
    risks: ['Global trade downturn', 'Currency swings'],
    financials: { revenue: '₹1,250 Cr', profit: '₹105 Cr', margin: '8.4%' }
  },
  {
    id: '30',
    name: 'TerraBuild Infra',
    symbol: 'TERRAINF',
    status: 'Closed',
    openDate: '2021-09-18',
    closeDate: '2021-09-21',
    listingDate: '2021-09-30',
    priceBand: '₹140 - ₹150',
    lotSize: 95,
    issueSize: '500 Cr',
    gmp: 18,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 4.2, nii: 5.1, retail: 3.6, total: 4.5 },
    listingPrice: 158,
    currentPrice: 172,
    description: 'EPC contractor with focus on industrial parks.',
    strengths: ['Order book visibility', 'Experienced execution'],
    risks: ['Commodity prices', 'Client concentration'],
    financials: { revenue: '₹1,400 Cr', profit: '₹115 Cr', margin: '8.2%' }
  },
  {
    id: '31',
    name: 'Nimbus Software',
    symbol: 'NIMSOFT',
    status: 'Closed',
    openDate: '2021-08-22',
    closeDate: '2021-08-25',
    listingDate: '2021-09-03',
    priceBand: '₹600 - ₹640',
    lotSize: 20,
    issueSize: '1,200 Cr',
    gmp: 140,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 70.2, nii: 90.1, retail: 38.6, total: 66.0 },
    listingPrice: 860,
    currentPrice: 905,
    description: 'Cloud-native ERP provider for manufacturing SMEs.',
    strengths: ['Recurring SaaS revenue', 'Global partners'],
    risks: ['Pricing pressure', 'Cyber threats'],
    financials: { revenue: '₹1,350 Cr', profit: '₹260 Cr', margin: '19.3%' }
  },
  {
    id: '32',
    name: 'Summit Foods',
    symbol: 'SUMFOOD',
    status: 'Closed',
    openDate: '2021-07-12',
    closeDate: '2021-07-15',
    listingDate: '2021-07-23',
    priceBand: '₹220 - ₹235',
    lotSize: 70,
    issueSize: '650 Cr',
    gmp: 12,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 3.8, nii: 4.2, retail: 2.9, total: 3.6 },
    listingPrice: 248,
    currentPrice: 238,
    description: 'Packaged foods company with frozen ready-to-eat line.',
    strengths: ['Export channels', 'Product innovation'],
    risks: ['Commodity inflation', 'Brand competition'],
    financials: { revenue: '₹1,150 Cr', profit: '₹88 Cr', margin: '7.6%' }
  },
  {
    id: '33',
    name: 'Radiant MedTech',
    symbol: 'RADMED',
    status: 'Closed',
    openDate: '2021-06-05',
    closeDate: '2021-06-08',
    listingDate: '2021-06-17',
    priceBand: '₹420 - ₹440',
    lotSize: 32,
    issueSize: '720 Cr',
    gmp: 95,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 38.5, nii: 60.4, retail: 20.5, total: 40.2 },
    listingPrice: 585,
    currentPrice: 610,
    description: 'Medical technology OEM manufacturing imaging devices.',
    strengths: ['USFDA approvals', 'High entry barriers'],
    risks: ['Supply chain disruptions', 'Fx exposure'],
    financials: { revenue: '₹900 Cr', profit: '₹170 Cr', margin: '18.9%' }
  },
  {
    id: '34',
    name: 'Falcon Retail',
    symbol: 'FALRET',
    status: 'Closed',
    openDate: '2021-05-10',
    closeDate: '2021-05-13',
    listingDate: '2021-05-21',
    priceBand: '₹90 - ₹95',
    lotSize: 150,
    issueSize: '750 Cr',
    gmp: -8,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 0.7, nii: 0.5, retail: 0.6, total: 0.65 },
    listingPrice: 88,
    currentPrice: 92,
    description: 'Value retail format with focus on apparel basics.',
    strengths: ['Lean supply chain', 'Tier-3 expansion'],
    risks: ['Working capital strain', 'Consumer slowdown'],
    financials: { revenue: '₹1,600 Cr', profit: '₹60 Cr', margin: '3.8%' }
  },
  {
    id: '35',
    name: 'Horizon Textiles',
    symbol: 'HORZTEX',
    status: 'Closed',
    openDate: '2021-04-12',
    closeDate: '2021-04-15',
    listingDate: '2021-04-23',
    priceBand: '₹150 - ₹160',
    lotSize: 95,
    issueSize: '480 Cr',
    gmp: 28,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 5.5, nii: 7.8, retail: 3.5, total: 5.9 },
    listingPrice: 185,
    currentPrice: 178,
    description: 'Integrated textile mill exporting home furnishings.',
    strengths: ['Integrated operations', 'Export incentives'],
    risks: ['Cotton price swings', 'FX fluctuation'],
    financials: { revenue: '₹900 Cr', profit: '₹70 Cr', margin: '7.8%' }
  },
  {
    id: '36',
    name: 'Vector Mobility',
    symbol: 'VECTORM',
    status: 'Closed',
    openDate: '2021-03-08',
    closeDate: '2021-03-11',
    listingDate: '2021-03-19',
    priceBand: '₹260 - ₹270',
    lotSize: 65,
    issueSize: '900 Cr',
    gmp: 55,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 18.5, nii: 24.1, retail: 12.4, total: 17.9 },
    listingPrice: 340,
    currentPrice: 322,
    description: 'Electric-mobility component maker for OEMs.',
    strengths: ['EV tailwinds', 'OEM partnerships'],
    risks: ['Technology obsolescence', 'Capex heavy'],
    financials: { revenue: '₹1,200 Cr', profit: '₹150 Cr', margin: '12.5%' }
  },
  {
    id: '37',
    name: 'Aurora Education',
    symbol: 'AURORAED',
    status: 'Closed',
    openDate: '2021-02-10',
    closeDate: '2021-02-13',
    listingDate: '2021-02-22',
    priceBand: '₹310 - ₹320',
    lotSize: 70,
    issueSize: '400 Cr',
    gmp: 15,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 2.2, nii: 3.1, retail: 1.8, total: 2.4 },
    listingPrice: 335,
    currentPrice: 318,
    description: 'Hybrid learning platform with test-prep focus.',
    strengths: ['Content IP', 'PAN-India centers'],
    risks: ['High CAC', 'Offline competition'],
    financials: { revenue: '₹520 Cr', profit: '₹48 Cr', margin: '9.2%' }
  },
  {
    id: '38',
    name: 'Prime Warehousing',
    symbol: 'PRIMEWH',
    status: 'Closed',
    openDate: '2021-01-05',
    closeDate: '2021-01-08',
    listingDate: '2021-01-18',
    priceBand: '₹130 - ₹140',
    lotSize: 110,
    issueSize: '550 Cr',
    gmp: 22,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 6.8, nii: 9.5, retail: 4.2, total: 7.1 },
    listingPrice: 165,
    currentPrice: 180,
    description: 'Industrial warehousing and park operator.',
    strengths: ['Tenant stickiness', 'REIT-ready assets'],
    risks: ['Leasing cycles', 'Interest rate risk'],
    financials: { revenue: '₹780 Cr', profit: '₹90 Cr', margin: '11.5%' }
  },
  {
    id: '39',
    name: 'Stellar Entertainment',
    symbol: 'STELLAR',
    status: 'Closed',
    openDate: '2020-12-07',
    closeDate: '2020-12-10',
    listingDate: '2020-12-18',
    priceBand: '₹200 - ₹210',
    lotSize: 80,
    issueSize: '650 Cr',
    gmp: 45,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 10.5, nii: 15.6, retail: 8.9, total: 11.2 },
    listingPrice: 275,
    currentPrice: 260,
    description: 'Live events and OTT content studio.',
    strengths: ['IP library', 'Multiple distribution channels'],
    risks: ['Cyclic ad spends', 'Production delays'],
    financials: { revenue: '₹1,050 Cr', profit: '₹130 Cr', margin: '12.4%' }
  },
  {
    id: '40',
    name: 'Crest Pharma',
    symbol: 'CRESTPH',
    status: 'Closed',
    openDate: '2020-11-05',
    closeDate: '2020-11-09',
    listingDate: '2020-11-18',
    priceBand: '₹480 - ₹500',
    lotSize: 30,
    issueSize: '1,300 Cr',
    gmp: 160,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 62.5, nii: 80.1, retail: 45.5, total: 64.2 },
    listingPrice: 750,
    currentPrice: 810,
    description: 'Specialty pharma company focused on oncology generics.',
    strengths: ['US filings pipeline', 'High margins'],
    risks: ['Regulatory inspections', 'Pricing pressure'],
    financials: { revenue: '₹2,400 Cr', profit: '₹420 Cr', margin: '17.5%' }
  },
  {
    id: '41',
    name: 'Titan AgroChem',
    symbol: 'TITANAG',
    status: 'Closed',
    openDate: '2020-10-12',
    closeDate: '2020-10-15',
    listingDate: '2020-10-23',
    priceBand: '₹210 - ₹225',
    lotSize: 85,
    issueSize: '550 Cr',
    gmp: 30,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 9.5, nii: 12.6, retail: 5.9, total: 9.8 },
    listingPrice: 265,
    currentPrice: 250,
    description: 'Agro chemical company with export focus.',
    strengths: ['Diversified product mix', 'Distribution reach'],
    risks: ['Monsoon dependency', 'Regulatory approvals'],
    financials: { revenue: '₹1,000 Cr', profit: '₹120 Cr', margin: '12.0%' }
  },
  {
    id: '42',
    name: 'Beacon Insurance',
    symbol: 'BEACON',
    status: 'Closed',
    openDate: '2020-09-05',
    closeDate: '2020-09-08',
    listingDate: '2020-09-17',
    priceBand: '₹360 - ₹380',
    lotSize: 40,
    issueSize: '1,000 Cr',
    gmp: 42,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 25.2, nii: 30.1, retail: 12.8, total: 23.4 },
    listingPrice: 430,
    currentPrice: 445,
    description: 'Tech-led insurance company with omnichannel distribution.',
    strengths: ['Strong solvency ratios', 'Digital acquisition'],
    risks: ['Underwriting cycles', 'Competitive pricing'],
    financials: { revenue: '₹3,200 Cr', profit: '₹260 Cr', margin: '8.1%' }
  },
  {
    id: '43',
    name: 'Nova Utilities',
    symbol: 'NOVAUTL',
    status: 'Closed',
    openDate: '2020-08-10',
    closeDate: '2020-08-13',
    listingDate: '2020-08-21',
    priceBand: '₹120 - ₹130',
    lotSize: 115,
    issueSize: '700 Cr',
    gmp: 8,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 1.8, nii: 2.6, retail: 1.7, total: 1.95 },
    listingPrice: 135,
    currentPrice: 140,
    description: 'Mini-hydel and captive power operator.',
    strengths: ['Stable cash flows', 'Government incentives'],
    risks: ['Seasonal output', 'Tariff revisions'],
    financials: { revenue: '₹620 Cr', profit: '₹55 Cr', margin: '8.9%' }
  },
  {
    id: '44',
    name: 'Vanguard Devices',
    symbol: 'VANGD',
    status: 'Closed',
    openDate: '2020-07-05',
    closeDate: '2020-07-08',
    listingDate: '2020-07-17',
    priceBand: '₹410 - ₹430',
    lotSize: 28,
    issueSize: '920 Cr',
    gmp: 70,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 32.2, nii: 48.1, retail: 18.7, total: 30.4 },
    listingPrice: 580,
    currentPrice: 600,
    description: 'Consumer electronics and wearables manufacturer.',
    strengths: ['ODM partnerships', 'Strong brand recall'],
    risks: ['Import dependency', 'Rapid tech cycles'],
    financials: { revenue: '₹1,650 Cr', profit: '₹200 Cr', margin: '12.1%' }
  },
  {
    id: '45',
    name: 'Eclipse Fashion',
    symbol: 'ECLFASH',
    status: 'Closed',
    openDate: '2020-06-12',
    closeDate: '2020-06-15',
    listingDate: '2020-06-24',
    priceBand: '₹150 - ₹160',
    lotSize: 100,
    issueSize: '420 Cr',
    gmp: 5,
    gmpUpdateDate: 'Closed',
    subscription: { qib: 1.1, nii: 1.6, retail: 1.2, total: 1.3 },
    listingPrice: 162,
    currentPrice: 150,
    description: 'Fast fashion apparel exporter for global brands.',
    strengths: ['Quick design cycles', 'Diversified buyers'],
    risks: ['Demand volatility', 'Compliance costs'],
    financials: { revenue: '₹780 Cr', profit: '₹52 Cr', margin: '6.7%' }
  }
];